# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        NB\CommonBundle\Entity\Administrador: { algorithm: bcrypt, cost: 4 }
        NB\CommonBundle\Entity\Usuario: { algorithm: bcrypt, cost: 4 }

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_USER:        [ROLE_TRABAJADOR, ROLE_SECRETARIO]
        ROLE_ADMIN:       [ROLE_ADMIN]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        administradores:
            entity: { class: NB\CommonBundle\Entity\Administrador, property: email }
        usuarios:
            entity: { class: NB\UserBundle\Entity\Usuario, property: email }
#        chain_provider:
#            chain:
#                providers: [usuarios]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            # activate different ways to authenticate
#
#            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            #http_basic: ~
#
#            # https://symfony.com/doc/current/security/form_login_setup.html
#            #form_login: ~
        backend:
            pattern:        ^/backend/*
            provider:       administradores
            anonymous:      ~
            form_login:
                login_path: backend_login
                check_path: backend_login
                default_target_path: backend_homepage
                always_use_default_target_path: true
            logout:
                path:       /backend/logout
                target:     frontend_homepage
            remember_me:
                secret: "%secret%"
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
            switch_user: { role: ROLE_ADMIN }
        frontend:
            pattern:        ^/*
            provider:       usuarios
            anonymous:      true
            form_login:
                login_path: frontend_login
                check_path: frontend_login
                default_target_path: frontend_homepage
                always_use_default_target_path: true
            logout:
                path:       /logout
                target:     frontend_homepage
            remember_me:
                secret: "%secret%"
                lifetime:   604800  # 604.800 = 3.600 * 24 * 7 = 1 semana
            switch_user: { role: ROLE_USER }
        main:
            anonymous: true
            
    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
#        - { path: ^/user/(%locales_app%)/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

#***************************************USERS*******************************************************************

        - { path: ^/privado/*, roles: [ROLE_TRABAJADOR] }
        - { path: ^/sec/*, roles: [ROLE_SECRETARIO] }

#***************************************BACKEND*******************************************************************

        - { path: ^/backend/(%locales_app%)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backend/*, roles: [ROLE_ADMIN] }

#***************************************OTHERS********************************************************************

        - { path: ^/*, roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_ANONYMOUSLY] }

    access_decision_manager:
        strategy: consensus