_frontend:
    path:     /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: frontend_homepage }

frontend_homepage:
    path:     /{_locale}/
    defaults: { _controller: FrontendBundle:Default:index }
    requirements:
        _locale: '%locales_app%'

frontend_login:
    path:     /{_locale}/login
    defaults: { _controller: FrontendBundle:Security:login }
    requirements:
        _locale: '%locales_app%'

frontend_logout:
    path:     /logout

fdispatch:
    path:     /dispatch/{template}
    defaults: { _controller: FrontendBundle:Default:dispatch }
    options:
        expose: true

#TESTING
frontend_privado:
    path:     /privado/{_locale}/
    defaults: { _controller: FrontendBundle:Default:index }
    requirements:
        _locale: '%locales_app%'

frontend_sec:
    path:     /sec/{_locale}/
    defaults: { _controller: FrontendBundle:Default:index }
    requirements:
        _locale: '%locales_app%'