backend_equipo_n_index:
    path:     /
    defaults: { _controller: "BackendBundle:EquipoN:index" }
    methods:  GET

backend_equipo_n_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:EquipoN:show" }
    methods:  GET

backend_equipo_n_new:
    path:     /new
    defaults: { _controller: "BackendBundle:EquipoN:new" }
    methods:  [GET, POST]

backend_equipo_n_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:EquipoN:edit" }
    methods:  [GET, POST]

backend_equipo_n_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:EquipoN:delete" }
    methods:  [GET]
