backend_equipo_index:
    path:     /
    defaults: { _controller: "BackendBundle:Equipo:index" }
    methods:  GET

backend_equipo_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Equipo:show" }
    methods:  GET

backend_equipo_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Equipo:new" }
    methods:  [GET, POST]

backend_equipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Equipo:edit" }
    methods:  [GET, POST]

backend_equipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Equipodelete" }
    methods:  [GET]
