backend_especialidad_index:
    path:     /
    defaults: { _controller: "BackendBundle:Especialidad:index" }
    methods:  GET

backend_especialidad_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Especialidad:show" }
    methods:  GET

backend_especialidad_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Especialidad:new" }
    methods:  [GET, POST]

backend_especialidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Especialidad:edit" }
    methods:  [GET, POST]

backend_especialidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Especialidad:delete" }
    methods:  DELETE
