backend_procedencia_n_index:
    path:     /
    defaults: { _controller: "BackendBundle:ProcedenciaN:index" }
    methods:  GET

backend_procedencia_n_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:ProcedenciaN:show" }
    methods:  GET

backend_procedencia_n_new:
    path:     /new
    defaults: { _controller: "BackendBundle:ProcedenciaN:new" }
    methods:  [GET, POST]

backend_procedencia_n_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:ProcedenciaN:edit" }
    methods:  [GET, POST]

backend_procedencia_n_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:ProcedenciaNdelete" }
    methods:  [GET]
