backend_prueba_index:
    path:     /
    defaults: { _controller: "BackendBundle:Prueba:index" }
    methods:  GET

backend_prueba_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Prueba:show" }
    methods:  GET

backend_prueba_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Prueba:new" }
    methods:  [GET, POST]

backend_prueba_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Prueba:edit" }
    methods:  [GET, POST]

backend_prueba_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Prueba:delete" }
    methods:  [GET]
