backend_homepage:
    path:     /{_locale}/
    defaults: { _controller: BackendBundle:Default:index }
    requirements:
        _locale: '%locales_app%'

backend_login:
    path:     /{_locale}/login
    defaults: { _controller: BackendBundle:Security:login }
    requirements:
        _locale: '%locales_app%'

backend_logout:
    path:     /logout

bdispatch:
    path:     /dispatch/{template}
    defaults: { _controller: BackendBundle:Default:dispatch }
    options:
        expose: true

backend_equipo:
    resource: "@BackendBundle/Resources/config/routing/equipo.yml"
    prefix:   /{_locale}/equipo/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_prueba:
    resource: "@BackendBundle/Resources/config/routing/prueba.yml"
    prefix:   /{_locale}/prueba/
    defaults: { _locale: '%locale%' }
    requirements:
        _locale: '%locales_app%'

backend_especialidad:
    resource: "@BackendBundle/Resources/config/routing/especialidad.yml"
    prefix:   /{_locale}/especialidad
    requirements:
            _locale: '%locales_app%'

backend_procedencia:
    resource: "@BackendBundle/Resources/config/routing/procedencia.yml"
    prefix:   /procedencia

