backend_homepage:
    path:     /{_locale}/
    defaults: { _controller: BackendBundle:Default:index }
    requirements:
        _locale: '%locales_app%'

backend_login:
    path:     /{_locale}/login
    defaults: { _controller: BackendBundle:Security:login }
    requirements:
        _locale: '%locales_app%'

backend_logout:
    path:     /logout