backend_homepage:
    path:     /{_locale}/
    defaults: { _controller: BackendBundle:Default:index }
    requirements:
        _locale: '%locales_app%'

backend_login:
    path:     /{_locale}/login
    defaults: { _controller: BackendBundle:Security:login }
    requirements:
        _locale: '%locales_app%'

backend_logout:
    path:     /logout

bdispatch:
    path:     /dispatch/{template}
    defaults: { _controller: BackendBundle:Default:dispatch }
    options:
        expose: true

common_equipo:
    resource: "@BackendBundle/Resources/config/routing/equipo.yml"
    prefix:   /equipo

common_prueba:
    resource: "@BackendBundle/Resources/config/routing/prueba.yml"
    prefix:   /prueba

common_especialidad:
    resource: "@BackendBundle/Resources/config/routing/especialidad.yml"
    prefix:   /especialidad

common_procedencia:
    resource: "@BackendBundle/Resources/config/routing/procedencia.yml"
    prefix:   /procedencia

