<?php

namespace NB\BackendBundle\Controller;

use NB\CommonBundle\Controller\NomenclatureController;
use NB\CommonBundle\Entity\Equipo;
use NB\CommonBundle\Form\ProcedenciaType;
use NB\CommonBundle\Util\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Equipo controller.
 *
 */
class ProcedenciaNController extends NomenclatureController
{
    /**
     * ¿Cómo desea nombrar la página?
     * @return string
     */
    public function getTitle()
    {
        // TODO: Implement getTitle() method.
        return 'Procedencia';
    }

    public function getEntityName()
    {
        // TODO: Implement getEntityName() method.
        return Entity::PROCEDENCIA;
    }

    /**
     * El prefijo de las rutas del CRUD q genera symfony
     * @return string
     */
    public function getRoutePrefix()
    {
        // TODO: Implement getRoutePrefix() method.
        return 'backend_procedencia_n';
    }

    public function getFormTypeClass()
    {
        return ProcedenciaType::class; // TODO: Change the autogenerated stub
    }

    public function defaultKeysFilter()
    {
        return array('id' => 'text', 'nombre' => 'text', 'descripcion' => 'text', 'fueraProvincia' => 'bool'); // TODO: Change the autogenerated stub
    }

    public function defaultKeysI18n()
    {
        return ['id' => $this->get('translator')->trans('nomenclador.id', [], 'common'),
            'nombre' => $this->get('translator')->trans('nomenclador.nombre', [], 'common'),
            'descripcion' => $this->get('translator')->trans('nomenclador.descripcion', [], 'common'),
            'fueraProvincia' => $this->get('translator')->trans('nomenclador.fueraProvincia', [], 'common')
        ]; // TODO: Change the autogenerated stub
    }


}
