prueba_index:
    path:     /{_locale}
    defaults: { _controller: "CommonBundle:Prueba:index" }
    methods:  GET
    requirements:
            _locale: '%locales_app%'

prueba_show:
    path:     /{_locale}/{id}/show
    defaults: { _controller: "CommonBundle:Prueba:show" }
    methods:  GET
    requirements:
            _locale: '%locales_app%'

prueba_new:
    path:     /{_locale}/new
    defaults: { _controller: "CommonBundle:Prueba:new" }
    methods:  [GET, POST]
    requirements:
            _locale: '%locales_app%'

prueba_edit:
    path:     /{_locale}/{id}/edit
    defaults: { _controller: "CommonBundle:Prueba:edit" }
    methods:  [GET, POST]
    requirements:
            _locale: '%locales_app%'

prueba_delete:
    path:     /{_locale}/{id}/delete
    defaults: { _controller: "CommonBundle:Prueba:delete" }
    methods:  DELETE
    requirements:
            _locale: '%locales_app%'
